name: GitHub Actions CI

on: [push]

# TODO: How do we just build on PRs against master or open PRs?
# push:
#   branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install + checks
      run: |
        yarn --version
        yarn install --frozen-lockfile
        yarn check-ci
        codecov
      env:
        CI: true
